# Project information
site_name: License Manager
site_url: https://license-manager.netified.io
site_author: Thomas ILLIET

# Repository
repo_name: netified/license-manager
repo_url: https://github.com/netified/license-manager

# Copyright
copyright: Copyright &copy; 2022 Netified

# Configuration
theme:
  language: en
  name: material

  # Static files
  static_templates:
    - 404.html

  features:
    - navigation.prune
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - search.highlight
    - search.share
    - search.suggest

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Theme palette configuration
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/netified
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/netifiedandco
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/netifiedandco
    - icon: fontawesome/solid/cube
      link: https://www.nuget.org/profiles/netifiedandco  
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
      
# Plugin
plugins:
  - search

# Extension
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
# Page tree
nav:
    - Home: index.md