# Project information
site_name: License Manager
site_url: https://license-manager.netified.io
site_author: Thomas ILLIET

# Repository
repo_name: netified/license-manager
repo_url: https://github.com/netified/license-manager

# Copyright
copyright: Copyright &copy; 2022 Netified

# Configuration
theme:
  name: material

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/netified
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/netifiedandco
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/netifiedandco
    - icon: fontawesome/solid/cube
      link: https://www.nuget.org/profiles/netifiedandco  

# Extension
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences