name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install git+https://${GH_TOKEN}@github.com/netified/mkdocs-material.git
      - name: Build documentation for docker
        run: mkdocs build --site-dir site --clean
      - name: Upload build output
        uses: actions/upload-artifact@v3
        with:
          name: mkdocs-build-output
          path: ./site
      - name: Deploy to github pages
        run: mkdocs gh-deploy --force
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
         registry: ghcr.io
         username: ${{github.actor}}
         password: ${{secrets.GITHUB_TOKEN}} 
      - name: Publish docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/netified/license-manager:latest
            ghcr.io/netified/license-manager:${{github.run_number}}
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }} 